#!/usr/bin/env bash

CONTAINER_TAG=jobs-tests

set -e
echo "Building htcondor-jobs testing container..."
docker build --quiet -t ${CONTAINER_TAG} --file tests/_inf/Dockerfile .
docker run -it --rm ${CONTAINER_TAG} $@
