#!/usr/bin/env bash

CONTAINER_TAG='htcondor-jobs-dev'

set -e

docker build -t ${CONTAINER_TAG} --file docker/Dockerfile .

docker run -it --rm --mount type=bind,src="$PWD",dst=/home/dev/htcondor-jobs -p 8000:8000 ${CONTAINER_TAG} $@
